// This file is auto-generated by Rails
///!!!!Stimulusコントローラーのエントリーポイント!!!!!///
// Import Stimulus application

import { Application } from "@hotwired/stimulus";

const application = Application.start();

application.debug = false;
//stimulusをグローバルに公開。
window.Stimulus = application; 

export { application }


// 使用するcontrollerを定義。
import ExampleController from "./example_controller";
application.register("example", ExampleController);
//↑pin "controllers/example_controller", to: "controllers/example_controller.js"

