version: '3.8'

services:
  web:
    build: .
    command: sh -c "service cron start && bin/rails db:migrate && rails server -b 0.0.0.0 -p 3001"
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    environment:
      - RAILS_ENV=development
