#Railsアプリ内で使うDBの設定(アプリがDBに接続するための設定)(Railsアプリの視点)
#docker-composは、Dockerのネットワーク内で使う。(dockerインフラの視点)
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DATABASE_HOST"] || 'db' %> # hostが設定されていない場合はnil(render対策)


development:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  database: <%= ENV.fetch("DATABASE_NAME", "myapp_development") %>

test:
  <<: *default
  host: <%= ENV.fetch("DATABASE_HOST", "localhost") %>
  username: <%= ENV.fetch("DATABASE_USER", "postgres") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "password") %>
  database: myapp_test

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DATABASE_NAME"] %>
  pool: 5
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  port: 5432